
server:
  port: 1001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    hikari:
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 指定namespace
        #namespace: 560bad5f-a229-4792-8332-e65b353b166e
        # 指定集群名称
        #cluster-name: NJ
  application:
    name: user-center

#ribbon 将要调用的服务
content-center:
  ribbon:
    #使用随机策略   轮询：RoundRobinRule
    NFLoadBalanceRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  #使用饥饿加载 解决首次请求过慢的问题
  eager-load:
    enabled: true
    #多个使用,号分隔
    clients: content-center

#日志级别
logging:
  level:
    com.momo.usercenter: debug
#配置feign的日志 才会打印 否则feign调用不会打印日志
feign:
  client:
    config:
      #想要调用的微服务名称
      #content-center:
      #全局配置
      default:
        #生产环境使用basic 开发环境用full（损耗性能）
        loggerLevel: full
  httpclient:
    #让feign使用apache httpclient做请求（连接池 性能提升15%）
    #而不是默认的urlconnection(默认的性能比restTemplate差50%左右)
    enabled: true
    #feign最大链接数
    max-connections: 200
    #feign单个路径的最大连接数
    max-connections-per-route: 50
